version: 0.16.{build}
pull_requests:
  do_not_increment_build_number: true
configuration: Release
shallow_clone: true
clone_depth: 10
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  publish_nuget: true
  verbosity: quiet
test:
  assemblies:
    only:
    - Build\Testing\**\*Tests.dll
artifacts:
- path: Build\Nuget\*.nupkg
  name: NugetPackage
deploy:
- provider: NuGet
  api_key:
    secure: 2SwDMmXZZtgoLWsldKZ8GCu9rZXpO5quTYtSNJQSeeiqDjnmo0OfutNVcH3jsfpj
  artifact: 'NugetPackage'
  on:
    branch: release
notifications:
- provider: Email
  to:
  - ericnewton76@gmail.com
  subject: Gmaps-api-net build completed.
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true

-environment:
 -  appveyor_rdp_password: Letmein1!
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
